name: merge-to-main
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Set up the environment
        uses: ./.github/workflows/setup-poetry

      - name: Run checks
        uses: ./.github/workflows/checks

  tox:
    runs-on: ubuntu-latest
    needs: quality
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Set up the environment
        uses: ./.github/workflows/setup-poetry
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test with tox
        run: |
          source .venv/bin/activate
          poetry add tox-gh-actions
          tox
